version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest  # Use the appropriate image for Ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: always

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    network_mode: host
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    restart: always

volumes:
  open-webui:
